In [4]:
import numpy as np
import os
import sklearn.preprocessing

In [30]:
def OneHot(a):
    height,width = a.shape
    a = a.flatten()
    a = a.astype(int)
    label_binarizer = sklearn.preprocessing.LabelBinarizer()
    label_binarizer.fit(range(max(a)+1))
    b = label_binarizer.transform(a)
    b = b.reshape((height,width,a.max()+1))
    return b


In [31]:
a = np.array([[1,2,3,4],[3,4,1,2]])
OneHot(a)

array([[[0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]],

       [[0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0]]])

In [32]:
dir = '/media/sf_TestImageDataBase/training/labels/'

In [29]:
for file in os.listdir(dir):
    if file.endswith(".npy"):
        directory = os.path.join(dir, file)
        inpt = np.load(directory)
        mat = OneHot(inpt)
        out_name = directory[:-4]    
        np.save('{}'.format(out_name + 'onehot'),mat)

arm_friday_21_october.npy
/media/sf_TestImageDataBase/training/labels/arm_friday_21_october.npy
1244
[[1 0 0]
 [1 0 0]
 [1 0 0]
 ...
 [1 0 0]
 [1 0 0]
 [1 0 0]]
arm_i1_thursday20.npy
/media/sf_TestImageDataBase/training/labels/arm_i1_thursday20.npy
1296
[[1 0 0]
 [1 0 0]
 [1 0 0]
 ...
 [1 0 0]
 [1 0 0]
 [1 0 0]]
arm_i1_thursday20_asg.npy
/media/sf_TestImageDataBase/training/labels/arm_i1_thursday20_asg.npy
1276
[[1 0 0]
 [1 0 0]
 [1 0 0]
 ...
 [1 0 0]
 [1 0 0]
 [1 0 0]]
asg_foils_donor_friday28.npy
/media/sf_TestImageDataBase/training/labels/asg_foils_donor_friday28.npy
1324
[[0 1 0]
 [0 1 0]
 [0 1 0]
 ...
 [1 0 0]
 [1 0 0]
 [1 0 0]]
hand_friday_21_october.npy
/media/sf_TestImageDataBase/training/labels/hand_friday_21_october.npy
1282
[[1 0 0]
 [1 0 0]
 [1 0 0]
 ...
 [1 0 0]
 [1 0 0]
 [1 0 0]]
hand_june2017.npy
/media/sf_TestImageDataBase/training/labels/hand_june2017.npy
2640
[[0 0 1]
 [0 0 1]
 [0 0 1]
 ...
 [1 0 0]
 [1 0 0]
 [1 0 0]]
Knee_cropped.npy
/media/sf_TestImageDataBase/train